### ISSUE TITLE
cannot import name 'GevPixelFormat' from 'pygigev'

### ISSUE THREAD

**Issue by arnthorg** [AdamSanderson93/PyGigEV#1]
```
:~/PyGigEV$ python3.8 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pygigev import PyGigEV as gev, GevPixelFormat, color_conversions
ImportError: cannot import name 'GevPixelFormat' from 'pygigev' (/usr/local/lib/python3.8/dist-packages/pygigev.cpython-38-x86_64-linux-gnu.so)
:~/PyGigEV$ 
```

also the default for USE_CYTHON is True and not False as per the readme.MD :)

**Comment by arnthorg** [comment]
when I remove GevPixelFormat and color_conversion from the import I get 

```
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    ctx.GevSetFeatureValueAsString("ExposureTime", "5000")
  File "pygigev.pyx", line 254, in pygigev.PyGigEV.GevSetFeatureValueAsString
    if img is NULL or exitcode != decl.APIErrors.GEVLIB_OK:
AttributeError: 'bytes' object has no attribute 'c_str'
```

**Comment by AdamSanderson93** [comment]
Seems like its a python3 issue. I modified this from a python2.7 library and tested in 2.7. I'll give this a look and see what I can dig up.

Actually nevermind. Ran into an issue with 2.7 just now. Must be something else.

**Comment by arnthorg** [comment]
Thank you so much, this is amazing work! 

Do you have an idea of how much work it would be to have it work with two cameras simultaneously? 

best regards

**Comment by AdamSanderson93** [comment]
Once the code is working again it should work with two cameras, though this is untested. I think I have access to two cameras and will test this once I get the build functioning again.

**Comment by AdamSanderson93** [comment]
Fixed the import issue but have not been able to test. Will test this over the weekend and see about adding an example for multi-camera setups.

**Comment by arnthorg** [comment]
great, thank you. 

I'm having some issues with ctx.GevSetImageParameters()
```
>>> ctx.GevSetImageParameters(640, 400, 0, 0, 17301513)
'OK'
>>> ctx.GevGetImageParameters()
{'code': 0, 'width': 640, 'height': 15534097845715344, 'x_offset': 0, 'y_offset': 0, 'pixelFormat': (17301513, '0x1080009')}
```

the height seems to be read either read or set incorrectly which causes ctx.GevInitializeImageTransfer(10) to throw a `ValueError: Maximum allowed dimension exceeded`

**Comment by arnthorg** [comment]
great!, it works perfectly with the fixes you commited just now

**Comment by arnthorg** [comment]
didn't want to open a new issue, 
I tested with 2 cameras and it works great!
I sometimes get code -4 when opening the cameras but I think that's easy to work around.

quick & dirty test code: 
```python
import time
import cv2

# create new context to store native camera data
ctx = gev()
dtx = gev()

# print list of available cameras
print(ctx.GevGetCameraList())
print(dtx.GevGetCameraList())

# open the first detected camera - returns 'OK'
#   ctx.GevOpenCamera(cameraListIndex=0)
ctx.GevOpenCamera(cameraListIndex=0)
dtx.GevOpenCamera(cameraListIndex=1)

print(ctx.GevGetImageParameters())
print(dtx.GevGetImageParameters())


ctx.GevInitializeImageTransfer(10)
dtx.GevInitializeImageTransfer(10)

ctx.GevStartImageTransfer(-1)
dtx.GevStartImageTransfer(-1)
while True:
    print("cam0", ctx.GevWaitForNextImage(1))
    print("cam1", dtx.GevWaitForNextImage(1))
    print("\033[F\033[A\033[A")
    time.sleep(0.1)
```

**Comment by AdamSanderson93** [comment]
That's great to hear. I added the support for this early on but never had a chance to test it. I'll add a modified version of this to the repo.

**Comment by SergiDopazo** [comment]
Buenos días, es mi primera vez en Github espero estar haciendo la pregunta en el sitio correcto.

Mi primer problema es el mismo que describe el sr. @arnthorg :
from pygigev import PyGigEV as gev, GevPixelFormat, color_conversions
Uso Python 2.7
Mi segundo problema, aunque no use su programa y uso el del sr. @Jcramer. Solo obtengo imágenes en Blanco y negro, como puedo pasaré eso a Color?.

Muchas gracias por su aportación.

**Comment by SergiDopazo** [comment]
Good morning, it's my first time on Github I hope I'm asking the question in the right place.

My first problem is the same as Mr. @Arnthorg describes:
from pygigev import PyGigEV as gev, GevPixelFormat, color_conversions
I use Python 2.7
My second problem, even though I don't use your program and I use mr. @Jcramer. I only get images in Black and White, how can I convert that to Color ?.
Third problem, also in the Jcramer program when it has been running for a while it gives me a Backend error, and it looks very lagged.

Thank you very much for your support.

**Comment by arnthorg** [comment]
@SergiDopazo 
Try removing GevPixelFormat and color_conversions from the import line, if that's not the case then you need to check the python PATH to make sure that python can find the  .so file that's created by setup.py. 

for color conversion, assuming you're using bayer rg you can use cv2 cvtcolor, see https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.html

**Comment by AdamSanderson93** [comment]
Hello @SergiDopazo and @arnthorg,

That issue should have been fixed in the last push. If you're having issues please send me a copy of the printout just incase it is different. I thought I turned them into standard python items so it should be functional. The issue may be python2.7 as I am using the enum class for the GevPixelFormat which I don't think exists in 2.7.

For the color conversion I included a dictionary called color_conversions in which you can use the pixel format returned from GevGetImageParameters() and opencv's cvtColor function to convert it. I didn't test all of these conversions so hopefully they function properly.

I'll test it when I get the chance and include some sample code.

**Comment by AdamSanderson93** [comment]
@arnthorg Probably not the right place to ask this but out of curiosity what are you using this package for and is there anything you think should be added? I'm fixing this up for fun and am looking for more features to add.

**Comment by SergiDopazo** [comment]
Tomorrow I will review everything you have commented, thank you very much for your time and support.
Tomorrow afternoon I'll tell you about my progress.
Greetings

**Comment by SergiDopazo** [comment]
I use this for my final degree project, I will mention in my work your work @AdamSanderson93 and that of @jcramer, of course. But I am new to Ubuntu, and I am a bit lost.

**Comment by AdamSanderson93** [comment]
Sorry for the delay. I can't replicate the issue. Try using pip to install it with 'sudo pip install .'

I also added color conversions into the test.py file

**Comment by arnthorg** [comment]
> 
> 
> @arnthorg Probably not the right place to ask this but out of curiosity what are you using this package for and is there anything you think should be added? I'm fixing this up for fun and am looking for more features to add.

I'm using it for prototype submarine stereo camera.
