### ISSUE TITLE
GEV_STATUS

### ISSUE THREAD

**Issue by arnthorg** [AdamSanderson93/PyGigEV#3]
Hey, 

I'm running into similar problems with GEV_STATUS, I tried defining it as INT16 but I still get -32762 for some errors, and not the expected 0x800N, maybe some quirk with cython?

**Comment by AdamSanderson93** [comment]
These are the definitions from the gevapi.h file..

#define GEV_STATUS_SUCCESS					0x0000		//!< Requested operation was completed successfully.
#define GEV_STATUS_NOT_IMPLEMENTED		0x8001		//!< The request isn't supported by the device.
#define GEV_STATUS_INVALID_PARAMETER	0x8002		//!< At least one parameter provided in the command is invalid (or out of range) for the device
#define GEV_STATUS_INVALID_ADDRESS		0x8003		//!< An attempt was made to access a non existent address space location.
#define GEV_STATUS_WRITE_PROTECT			0x8004		//!< The addressed register must not be written.
#define GEV_STATUS_BAD_ALIGNMENT			0x8005		//!< A badly aligned address offset or data size was specified.
#define GEV_STATUS_ACCESS_DENIED			0x8006		//!< An attempt was made to access an address location which is currently/momentary not accessible.
#define GEV_STATUS_BUSY						0x8007		//!< A required resource to service the request isn't currently available. The request may be retried.
#define GEV_STATUS_LOCAL_PROBLEM			0x8008		//!< A internal problem in the device implementation occurred while processing the request. 
#define GEV_STATUS_MSG_MISMATCH			0x8009		//!< Message mismatch (request and acknowledge don't match)
#define GEV_STATUS_INVALID_PROTOCOL		0x800A		//!< This version of the GVCP protocol is not supported
#define GEV_STATUS_NO_MSG					0x800B		//!< No message received, timeout.
#define GEV_STATUS_PACKET_UNAVAILABLE	0x800C		//!< The request packet is not available anymore.
#define GEV_STATUS_DATA_OVERRUN			0x800D		//!< Internal memory of device overrun (typically for image acquisition)
#define GEV_STATUS_INVALID_HEADER		0x800E		//!< The message header is not valid. Some of its fields do not match the specificiation.

#define GEV_STATUS_ERROR					0x8FFF		//!< Generic error. 

It would likely be better defined as a UINT16. From converting that Int value to hex it appears you're getting an access denied error.

**Comment by AdamSanderson93** [comment]
@arnthorg wanted to verify if this has helped so I can close the issue. Any news?

**Comment by arnthorg** [comment]
Sorry for the delayed response. 

There are some problems with the exitcodes I'm not figuring out, I thought I could work around the problem by doing `return exitcode & 0x0F` in handleExitCode() which works most of the time but seems to go wonky sometimes. 

I have it now `ctypedef UINT16 GEV_STATUS` in decl.pyx but  when trying to connect to a camera that I've disconnected while running, so not accessible, I get the exitcode 65520 which is 0b1111111111110000 in binary, if I change it to INT32 I get -16 under the same circumstance, which is correct actually. `GEVLIB_ERROR_DEVICE_NOT_FOUND = -16  #// Device/camera specified was not found.`. 

final edit: It seems to be right when I have it as INT32 for some reason, I changed handleExitCode so that it just returns the exitcode. 
final final edit: so there seems to me there might be some mixup between GEV_STATUS and APIErrors which is defined in decl.pyx?


```
ctypedef stdint.int8_t INT8
ctypedef stdint.uint8_t UINT8
ctypedef stdint.int16_t INT16
ctypedef stdint.uint16_t UINT16
ctypedef bint BOOL
ctypedef stdint.int32_t INT32
ctypedef stdint.uint32_t UINT32
ctypedef stdint.int64_t INT64
ctypedef stdint.uint64_t UINT64

ctypedef UINT8* PUINT8
ctypedef UINT32* PUINT32

ctypedef UINT16 GEV_STATUS
```

**Comment by arnthorg** [comment]
So now GevWaitForImage gives the exit code -6 when there's not a frame available, `GEV_STATUS_ACCESS_DENIED 0x8006 //!< An attempt was made to access an address location which is currently/momentary not accessible.` which makes sense, `GEVLIB_ERROR_TIME_OUT = -6   #// Timed out waiting for a resource` also makes sense.
But when I disconnect the camera and it tries to reconnect I get 0x800b, `#define GEV_STATUS_NO_MSG 0x800B //!< No message received, timeout.`. 

so, I think there must be some mix up somewhere

**Comment by AdamSanderson93** [comment]
So does this issue happen if you hotplug the camera? I found some issue with this previously where the system takes a minute or two to clear everything when you unplug and replug the camera from the system. I believe this is a GigeV issue. It tends to just block up and require a hard stop to reconnect. I've had similar issue from the core C++ library.

**Comment by arnthorg** [comment]
I'm not sure actually, but with gev_status as INT32 the behavior is manageable, I sometimes get negative numbers and sometimes 0x800N which is fine :D
